# Generated by Django 4.2.11 on 2026-01-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(choices=[('GS', 'Grundschule'), ('MS', 'Mittelschule')], help_text='GS or MS program', max_length=2)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, help_text="For 'heimatnah' PDP matching")),
                ('semester_address', models.TextField(blank=True, help_text='For SFP/ZSP travel time calculation')),
                ('home_region', models.CharField(blank=True, max_length=100)),
                ('preferred_zone', models.CharField(blank=True, max_length=10)),
                ('pdp1_completed_date', models.DateField(blank=True, help_text='Date PDP I was completed', null=True)),
                ('pdp2_completed_date', models.DateField(blank=True, help_text='Date PDP II was completed', null=True)),
                ('sfp_completed_date', models.DateField(blank=True, help_text='Date SFP was completed', null=True)),
                ('zsp_completed_date', models.DateField(blank=True, help_text='Date ZSP was completed', null=True)),
                ('placement_status', models.CharField(choices=[('UNPLACED', 'Unplaced'), ('PLACED', 'Placed')], default='UNPLACED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('didactic_subject_1', models.ForeignKey(blank=True, help_text='Didaktikfach 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='didactic_1_students', to='subjects.subject')),
                ('didactic_subject_2', models.ForeignKey(blank=True, help_text='Didaktikfach 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='didactic_2_students', to='subjects.subject')),
                ('didactic_subject_3', models.ForeignKey(blank=True, help_text='Didaktikfach 3. (Target for ZSP in this MVP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='didactic_3_students', to='subjects.subject')),
                ('primary_subject', models.ForeignKey(blank=True, help_text="Student's primary teaching subject", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_students', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'), models.Index(fields=['program'], name='students_st_program_6d3e4e_idx'), models.Index(fields=['placement_status'], name='students_st_placeme_c64f9e_idx')],
            },
        ),
    ]
