# Generated by Django 4.2.25 on 2025-11-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(choices=[('GS', 'Grundschule'), ('MS', 'Mittelschule')], help_text='GS or MS program', max_length=2)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True)),
                ('home_region', models.CharField(blank=True, help_text='Region for Heimatnah matching', max_length=100)),
                ('preferred_zone', models.CharField(blank=True, help_text='Preferred distance zone', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('additional_subjects', models.ManyToManyField(blank=True, help_text='Additional subjects the student is qualified to teach', related_name='students', to='subjects.subject')),
                ('primary_subject', models.ForeignKey(help_text="Student's primary teaching subject", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_students', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPraktikumPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNPLACED', 'Unplaced'), ('IN_REVIEW', 'In Review'), ('PLACED', 'Placed'), ('COMPLETED', 'Completed')], default='UNPLACED', max_length=20)),
                ('availability_note', models.TextField(blank=True, help_text="e.g., 'I.d.R. im Herbst' for PDP I")),
                ('praktikum_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_preferences', to='subjects.praktikumtype')),
                ('preferred_schools', models.ManyToManyField(blank=True, related_name='preferred_by_students', to='schools.school')),
                ('preferred_subjects', models.ManyToManyField(blank=True, related_name='preferred_by_students', to='subjects.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praktikum_preferences', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Praktikum Preference',
                'verbose_name_plural': 'Student Praktikum Preferences',
                'unique_together': {('student', 'praktikum_type')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program'], name='students_st_program_6d3e4e_idx'),
        ),
    ]
