# Generated by Django 4.2.25 on 2025-11-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpraktikumpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentpraktikumpreference',
            name='praktikum_type',
        ),
        migrations.RemoveField(
            model_name='studentpraktikumpreference',
            name='preferred_schools',
        ),
        migrations.RemoveField(
            model_name='studentpraktikumpreference',
            name='preferred_subjects',
        ),
        migrations.RemoveField(
            model_name='studentpraktikumpreference',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='additional_subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='pdp1_completed_date',
            field=models.DateField(blank=True, help_text='Date PDP I was completed', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pdp2_completed_date',
            field=models.DateField(blank=True, help_text='Date PDP II was completed', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('UNPLACED', 'Unplaced'), ('PLACED', 'Placed')], default='UNPLACED', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_address',
            field=models.TextField(blank=True, help_text='For SFP/ZSP travel time calculation'),
        ),
        migrations.AddField(
            model_name='student',
            name='sfp_completed_date',
            field=models.DateField(blank=True, help_text='Date SFP was completed', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='zsp_completed_date',
            field=models.DateField(blank=True, help_text='Date ZSP was completed', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, help_text="For 'heimatnah' PDP matching"),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_zone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['placement_status'], name='students_st_placeme_c64f9e_idx'),
        ),
        migrations.DeleteModel(
            name='StudentPraktikumPreference',
        ),
    ]
