# Generated by Django 4.2.25 on 2025-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PraktikumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('PDP_I', 'PDP I (Pädagogisch-didaktisches Praktikum I)'), ('PDP_II', 'PDP II (Pädagogisch-didaktisches Praktikum II)'), ('SFP', 'SFP (Studienbegleitendes Fachpraktikum)'), ('ZSP', 'ZSP (Zusätzliches studienbegleitendes Praktikum)')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_block_praktikum', models.BooleanField(default=False, help_text='True for PDP I/II (allow Zone 3), False for SFP/ZSP (Zone 1/2 only)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Praktikum Type',
                'verbose_name_plural': 'Praktikum Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subject_group', models.CharField(blank=True, help_text='Subject grouping for GS/MS matching rules', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
    ]
