# Generated by Django 4.2.25 on 2025-11-03 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLSubjectAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True, help_text='Can this PL teach this subject for this Praktikum?')),
            ],
            options={
                'verbose_name': 'PL Subject Availability',
                'verbose_name_plural': 'PL Subject Availabilities',
            },
        ),
        migrations.CreateModel(
            name='PraktikumsLehrkraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(choices=[('GS', 'Grundschule'), ('MS', 'Mittelschule')], help_text='GS or MS program - must match student program', max_length=2)),
                ('schulamt', models.CharField(blank=True, help_text='Associated Schulamt (e.g., Passau-Land, Regen)', max_length=100)),
                ('max_students_per_praktikum', models.PositiveIntegerField(default=3, help_text='Max students per Praktikum session (same time slot)')),
                ('max_simultaneous_praktikum', models.PositiveIntegerField(default=2, help_text='Must supervise exactly 2 internships per year', validators=[django.core.validators.MaxValueValidator(2)])),
                ('besonderheiten', models.TextField(blank=True, help_text="Special conditions (e.g., '2 Mittwochs-Praktika')")),
                ('is_available', models.BooleanField(default=True, help_text='Available for assignment (false if ill/absent)')),
                ('notes', models.TextField(blank=True)),
                ('available_praktikum_types', models.ManyToManyField(help_text='Praktikum types this PL can supervise', related_name='available_pls', to='subjects.praktikumtype')),
                ('available_subjects', models.ManyToManyField(help_text='Subjects this PL can supervise', related_name='qualified_pls', through='praktikums_lehrkraft.PLSubjectAvailability', to='subjects.subject')),
                ('main_subject', models.ForeignKey(help_text='Primary teaching subject (Hauptfach)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_pls', to='subjects.subject')),
                ('school', models.ForeignKey(help_text='Current school assignment (cannot change mid-year)', on_delete=django.db.models.deletion.CASCADE, related_name='praktikumslehrkraefte', to='schools.school')),
            ],
            options={
                'verbose_name': 'Praktikumslehrkraft',
                'verbose_name_plural': 'Praktikumslehrkräfte',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='plsubjectavailability',
            name='pl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_availabilities', to='praktikums_lehrkraft.praktikumslehrkraft'),
        ),
        migrations.AddField(
            model_name='plsubjectavailability',
            name='praktikum_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_availabilities', to='subjects.praktikumtype'),
        ),
        migrations.AddField(
            model_name='plsubjectavailability',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_availabilities', to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='praktikumslehrkraft',
            index=models.Index(fields=['school', 'program'], name='praktikums__school__ec60cd_idx'),
        ),
        migrations.AddIndex(
            model_name='praktikumslehrkraft',
            index=models.Index(fields=['is_available'], name='praktikums__is_avai_2982c6_idx'),
        ),
        migrations.AddIndex(
            model_name='plsubjectavailability',
            index=models.Index(fields=['pl', 'praktikum_type', 'is_available'], name='praktikums__pl_id_ae757b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plsubjectavailability',
            unique_together={('pl', 'subject', 'praktikum_type')},
        ),
    ]
