# Generated by Django 4.2.11 on 2026-01-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraktikumsLehrkraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(choices=[('GS', 'Grundschule'), ('MS', 'Mittelschule')], help_text='GS or MS program', max_length=2)),
                ('preferred_praktika_raw', models.CharField(blank=True, help_text="Raw text from 'bevorzugte Praktika' column", max_length=255)),
                ('schulamt', models.CharField(blank=True, help_text='Associated Schulamt (e.g., Passau-Land, Regen)', max_length=100)),
                ('anrechnungsstunden', models.DecimalField(decimal_places=1, default=1.0, help_text="Credited hours (Anre-Std.). Standard is 1.0. '4 for 2' is 2.0.", max_digits=3)),
                ('current_year_notes', models.TextField(blank=True, help_text="Year-specific notes (e.g., 'Besonderheiten SJ 25_26')")),
                ('is_active', models.BooleanField(default=True, help_text='Master availability switch')),
                ('notes', models.TextField(blank=True, help_text='Internal system notes')),
                ('csv_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('available_praktikum_types', models.ManyToManyField(blank=True, help_text="Praktikum types this PL can supervise (Parsed from 'bevorzugte Praktika')", related_name='available_pls', to='subjects.praktikumtype')),
                ('available_subjects', models.ManyToManyField(blank=True, help_text="Subjects this PL can supervise this year (from the 'x' columns)", related_name='qualified_pls', to='subjects.subject')),
                ('main_subject', models.ForeignKey(blank=True, help_text='Primary teaching subject (Hauptfach) - Informational only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_pls', to='subjects.subject')),
                ('school', models.ForeignKey(help_text='Current school assignment', on_delete=django.db.models.deletion.CASCADE, related_name='praktikumslehrkraefte', to='schools.school')),
            ],
            options={
                'verbose_name': 'Praktikumslehrkraft',
                'verbose_name_plural': 'Praktikumslehrkräfte',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['school', 'program'], name='praktikums__school__ec60cd_idx'), models.Index(fields=['is_active'], name='praktikums__is_acti_1c8d26_idx')],
            },
        ),
    ]
