# Generated by Django 4.2.11 on 2026-01-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktikums_lehrkraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='history_pdp1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='history_pdp2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='history_sfp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='history_zsp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
