# Generated by Django 4.2.25 on 2025-11-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        ('praktikums_lehrkraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plsubjectavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='plsubjectavailability',
            name='pl',
        ),
        migrations.RemoveField(
            model_name='plsubjectavailability',
            name='praktikum_type',
        ),
        migrations.RemoveField(
            model_name='plsubjectavailability',
            name='subject',
        ),
        migrations.RemoveIndex(
            model_name='praktikumslehrkraft',
            name='praktikums__is_avai_2982c6_idx',
        ),
        migrations.RemoveField(
            model_name='praktikumslehrkraft',
            name='available_subjects',
        ),
        migrations.RemoveField(
            model_name='praktikumslehrkraft',
            name='besonderheiten',
        ),
        migrations.RemoveField(
            model_name='praktikumslehrkraft',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='praktikumslehrkraft',
            name='max_simultaneous_praktikum',
        ),
        migrations.RemoveField(
            model_name='praktikumslehrkraft',
            name='max_students_per_praktikum',
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='anrechnungsstunden',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text="Credited hours (Anre-Std.). Standard is 1.0. '4 for 2' is 2.0.", max_digits=3),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='csv_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='current_year_notes',
            field=models.TextField(blank=True, help_text="Year-specific notes (e.g., 'Besonderheiten SJ 25_26')"),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Master availability switch'),
        ),
        migrations.AlterField(
            model_name='praktikumslehrkraft',
            name='available_praktikum_types',
            field=models.ManyToManyField(blank=True, help_text="Praktikum types this PL can supervise (Parsed from 'bevorzugte Praktika')", related_name='available_pls', to='subjects.praktikumtype'),
        ),
        migrations.AlterField(
            model_name='praktikumslehrkraft',
            name='main_subject',
            field=models.ForeignKey(blank=True, help_text='Primary teaching subject (Hauptfach) - Informational only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_pls', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='praktikumslehrkraft',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal system notes'),
        ),
        migrations.AlterField(
            model_name='praktikumslehrkraft',
            name='program',
            field=models.CharField(choices=[('GS', 'Grundschule'), ('MS', 'Mittelschule')], help_text='GS or MS program', max_length=2),
        ),
        migrations.AlterField(
            model_name='praktikumslehrkraft',
            name='school',
            field=models.ForeignKey(help_text='Current school assignment', on_delete=django.db.models.deletion.CASCADE, related_name='praktikumslehrkraefte', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='praktikumslehrkraft',
            index=models.Index(fields=['is_active'], name='praktikums__is_acti_1c8d26_idx'),
        ),
        migrations.DeleteModel(
            name='PLSubjectAvailability',
        ),
    ]
