# Generated by Django 4.2.25 on 2025-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('praktikums_lehrkraft', '0002_alter_plsubjectavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='available_subjects',
            field=models.ManyToManyField(blank=True, help_text="Subjects this PL can supervise this year (from the 'x' columns)", related_name='qualified_pls', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='praktikumslehrkraft',
            name='preferred_praktika_raw',
            field=models.CharField(blank=True, help_text="Raw text from 'bevorzugte Praktika' column", max_length=255),
        ),
    ]
