# Generated by Django 4.2.25 on 2025-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('school_type', models.CharField(choices=[('GS', 'Grundschule (Primary School)'), ('MS', 'Mittelschule (Secondary School)')], max_length=2)),
                ('address', models.TextField()),
                ('district', models.CharField(help_text='Landkreis/District (e.g., Passau-Land, Regen)', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opnv_zone', models.CharField(choices=[('ZONE_1', 'Zone 1 (Close to University)'), ('ZONE_2', 'Zone 2 (Medium Distance)'), ('ZONE_3', 'Zone 3 (Far from University)')], help_text='Public transport accessibility zone', max_length=10)),
                ('travel_time_minutes', models.PositiveIntegerField(blank=True, help_text='Travel time from university in minutes', null=True)),
                ('max_block_praktikum_slots', models.PositiveIntegerField(default=0, help_text='Maximum slots for PDP I/II')),
                ('max_wednesday_praktikum_slots', models.PositiveIntegerField(default=0, help_text='Maximum slots for SFP/ZSP')),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school_type', 'opnv_zone'], name='schools_sch_school__6d8ce5_idx'), models.Index(fields=['district'], name='schools_sch_distric_d706f4_idx')],
            },
        ),
    ]
