# Generated by Django 4.2.11 on 2026-01-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('school_type', models.CharField(choices=[('GS', 'Grundschule (Primary School)'), ('MS', 'Mittelschule (Secondary School)'), ('GMS', 'Grund- und Mittelschule')], max_length=3)),
                ('district', models.CharField(help_text='Landkreis/District (e.g., Passau-Land, Regen)', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.IntegerField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3')], help_text='Official travel zone from university (1=closest, 3=farthest)')),
                ('opnv_code', models.CharField(blank=True, choices=[('4a', 'Up to 30 min'), ('4b', 'Up to 60 min')], help_text="Public transport code ('4a' or '4b') from the CSV", max_length=2)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display', max_digits=9, null=True)),
                ('geocoding_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('not_needed', 'Not Needed')], default='pending', help_text='Status of geocoding attempt', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school_type', 'zone'], name='schools_sch_school__0d4407_idx'), models.Index(fields=['district'], name='schools_sch_distric_d706f4_idx')],
            },
        ),
    ]
