# Generated by Django 4.2.25 on 2025-11-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='school',
            name='schools_sch_school__6d8ce5_idx',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='max_block_praktikum_slots',
        ),
        migrations.RemoveField(
            model_name='school',
            name='max_wednesday_praktikum_slots',
        ),
        migrations.RemoveField(
            model_name='school',
            name='opnv_zone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='travel_time_minutes',
        ),
        migrations.AddField(
            model_name='school',
            name='distance_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='opnv_code',
            field=models.CharField(blank=True, choices=[('4a', 'Up to 30 min'), ('4b', 'Up to 60 min')], help_text="Public transport code ('4a' or '4b') from the CSV", max_length=2),
        ),
        migrations.AddField(
            model_name='school',
            name='zone',
            field=models.IntegerField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3')], default=1, help_text='Official travel zone from university (1=closest, 3=farthest)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('GS', 'Grundschule (Primary School)'), ('MS', 'Mittelschule (Secondary School)'), ('GMS', 'Grund- und Mittelschule')], max_length=3),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_type', 'zone'], name='schools_sch_school__0d4407_idx'),
        ),
    ]
