# Generated by Django 4.2.25 on 2025-11-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_schools_sch_school__6d8ce5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display', max_digits=9, null=True),
        ),
    ]
