# Generated by Django 4.2.25 on 2025-11-03 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_academic_year', models.CharField(help_text="e.g., '2024/2025'", max_length=20, unique=True)),
                ('total_anrechnungsstunden_budget', models.DecimalField(decimal_places=2, default=210.0, help_text='Total credit hours budget (210 = 210 mentors × 2 Praktika each)', max_digits=6)),
                ('gs_budget_percentage', models.DecimalField(decimal_places=2, default=80.48, help_text='Percentage allocated to GS (e.g., 80.48%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ms_budget_percentage', models.DecimalField(decimal_places=2, default=19.52, help_text='Percentage allocated to MS (e.g., 19.52%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pdp_i_demand_deadline', models.DateField(blank=True, null=True)),
                ('pl_assignment_deadline', models.DateField(blank=True, null=True)),
                ('winter_semester_adjustment_date', models.DateField(blank=True, null=True)),
                ('university_name', models.CharField(default='Universität Passau', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the active academic year?')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'ordering': ['-current_academic_year'],
            },
        ),
    ]
