# Generated by Django 4.2.11 on 2026-01-23 20:38

from django.db import migrations, models
import system_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='core_subjects',
            field=models.JSONField(default=system_settings.models.default_core_subjects, help_text="List of core subject codes (e.g., ['D', 'MA'])"),
        ),
    ]
