# Generated by Django 4.2.25 on 2025-12-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('praktikums_lehrkraft', '0003_praktikumslehrkraft_available_subjects_and_more'),
        ('schools', '0003_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(default='2025/26', max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='praktikums_lehrkraft.praktikumslehrkraft')),
                ('practicum_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.praktikumtype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
            ],
            options={
                'unique_together': {('mentor', 'practicum_type', 'subject', 'academic_year')},
            },
        ),
    ]
