# Generated by Django 4.2.25 on 2026-01-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_studentassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentassignment',
            new_name='assignments_student_5f4794_idx',
            old_name='assignments_student_6e8f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentassignment',
            new_name='assignments_mentor__b26403_idx',
            old_name='assignments_mentor_i_e20c29_idx',
        ),
        migrations.RenameIndex(
            model_name='studentassignment',
            new_name='assignments_assignm_d7bae7_idx',
            old_name='assignments_assignme_7fcbbd_idx',
        ),
    ]
